version: "3"
services:
  squid:
    image: shnee/squid:mvp2
    container_name: squid
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=squid.shnee.net
      - VIRTUAL_PORT=4128
      - NETWORK_ACCESS=internal
      - TZ=America/New_York
      - CN=squid.shnee.net
      - O="Well Done. Systems"
      - OU=""
      - C=US
    ports:
      - "3128:3128"
      - "4128:4128"
    volumes:
      - ./log:/var/log/
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/cache
      - ./cert:/etc/squid-cert
    restart: unless-stopped
